import os

ARC_DO_Y1_EUR = [
    os.path.join("MEDIA", "ADVERTISE"),
    os.path.join("MEDIA", "BATTLE_START_CAPTION"),
    os.path.join("MEDIA", "CSE", "BRI"),
    os.path.join("MEDIA", "CSE", "FRA"),
    os.path.join("MEDIA", "CSE", "GER"),
    os.path.join("MEDIA", "CSE", "ITA"),
    os.path.join("MEDIA", "CSE", "SPA"),
    os.path.join("MEDIA", "INTRODUCTION"),
    os.path.join("MEDIA", "PAUSEMENU", "BRI"),
    os.path.join("MEDIA", "PAUSEMENU", "FRA"),
    os.path.join("MEDIA", "PAUSEMENU", "GER"),
    os.path.join("MEDIA", "PAUSEMENU", "ITA"),
    os.path.join("MEDIA", "PAUSEMENU", "SPA"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "IFC_COLO_MENU"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "IFC_OPTION"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "IFC_YK_RESULT"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "IFC_YK_STATUS01"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "MISSIONSUCC"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "TOKU_CHOICE"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "TOKU_NOTCHOICE"),
    os.path.join("MEDIA", "STAFFROLL"),
    os.path.join("MEDIA", "STGTALK"),
    os.path.join("MEDIA", "TALK"),
    os.path.join("MEDIA2", "AUTHOR")
]

ARC_DO_Y1 = [
    os.path.join("MEDIA", "ADVERTISE"),
    os.path.join("MEDIA", "BATTLE_START_CAPTION"),
    os.path.join("MEDIA", "CSE", "BRI"),
    os.path.join("MEDIA", "CSE", "FRA"),
    os.path.join("MEDIA", "CSE", "GER"),
    os.path.join("MEDIA", "CSE", "ITA"),
    os.path.join("MEDIA", "CSE", "JPN"),
    os.path.join("MEDIA", "CSE", "SPA"),
    os.path.join("MEDIA", "CSE", "USA"),
    os.path.join("MEDIA", "INTRODUCTION"),
    os.path.join("MEDIA", "PAUSEMENU", "BRI"),
    os.path.join("MEDIA", "PAUSEMENU", "FRA"),
    os.path.join("MEDIA", "PAUSEMENU", "GER"),
    os.path.join("MEDIA", "PAUSEMENU", "ITA"),
    os.path.join("MEDIA", "PAUSEMENU", "JPN"),
    os.path.join("MEDIA", "PAUSEMENU", "SPA"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "IFC_COLO_MENU"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "IFC_OPTION"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "IFC_YK_RESULT"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "IFC_YK_STATUS01"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "MISSIONSUCC"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "TOKU_CHOICE"),
    os.path.join("MEDIA", "PAUSEMENU", "TEX", "TOKU_NOTCHOICE"),
    os.path.join("MEDIA", "PAUSEMENU", "USA"),
    os.path.join("MEDIA", "STAFFROLL"),
    os.path.join("MEDIA", "TALK"),
    os.path.join("MEDIA2", "AUTHOR"),
    os.path.join("MEDIA3", "ARC")
]

TALK_SKIP_Y1 = [
    os.path.join("MEDIA", "TALK", "HOME", "TALK_HOMECLEAR"),
    os.path.join("MEDIA", "TALK", "HOME", "TALK_HOMEMENU"),
    os.path.join("MEDIA", "TALK", "HOME", "TALK_HOMEMOVIE"),
    os.path.join("MEDIA", "TALK", "PAUSE", "TALK_PAUSEMENU"),
    os.path.join("MEDIA2", "AUTHOR", "CAPTION"),
    os.path.join("MEDIA2", "AUTHOR", "CHAPTER"),
    os.path.join("MEDIA2", "AUTHOR", "OPENING"),
    os.path.join("MEDIA2", "AUTHOR", "SUB"),
]

TALK_SELF_Y1 = [
    os.path.join("MEDIA", "TALK", "ADVERTISE"),
    os.path.join("MEDIA", "TALK", "CAPTION"),
    os.path.join("MEDIA", "TALK", "CHARACTORINFO"),
    os.path.join("MEDIA", "TALK", "COLOSSEUM"),
    os.path.join("MEDIA", "TALK", "CONTINUE"),
    os.path.join("MEDIA", "TALK", "HOME", "TALK_HOMEMEMCARD"),
    os.path.join("MEDIA", "TALK", "MEMCARD"),
    os.path.join("MEDIA", "TALK", "MINIGAME"),
    os.path.join("MEDIA", "TALK", "OPTION"),
    os.path.join("MEDIA", "TALK", "PAUSE", "TALK_PAUSECELLULAR"),
    os.path.join("MEDIA", "TALK", "PAUSE", "TALK_PAUSEMAP"),
    os.path.join("MEDIA", "TALK", "PAUSE", "TALK_PAUSEMISSION"),
    os.path.join("MEDIA", "TALK", "PAUSE", "TALK_PAUSERELATION"),
    os.path.join("MEDIA", "TALK", "PAUSE", "TALK_PAUSESTATUS"),
    os.path.join("MEDIA", "TALK", "SELECT", "TALK_SELECTMENU"),
    os.path.join("MEDIA", "TALK", "TITLE"),
    os.path.join("MEDIA", "TALK", "TUTORIAL"),
    os.path.join("MEDIA", "TALK", "ULTIMATEBOX"),
]

TALK_HOLD_Y1 = [
]

ARC_DO_Y2 = [
    os.path.join("MEDIA", "ADVERTISE"),
    os.path.join("MEDIA", "BATTLE_START_CAPTION"),
    os.path.join("MEDIA", "CSE", "BRI"),
    os.path.join("MEDIA", "CSE", "FRA"),
    os.path.join("MEDIA", "CSE", "GER"),
    os.path.join("MEDIA", "CSE", "ITA"),
    os.path.join("MEDIA", "CSE", "JPN"),
    os.path.join("MEDIA", "CSE", "SPA"),
    os.path.join("MEDIA", "CSE", "TEX", "CHANGE_DISK"),
    os.path.join("MEDIA", "CSE", "TEX", "MISSIONFAIL"),
    os.path.join("MEDIA", "CSE", "TEX", "MISSIONSUCC"),
    os.path.join("MEDIA", "CSE", "TEX", "MJ_MANUAL"),
    os.path.join("MEDIA", "CSE", "TEX", "OPTION"),
    os.path.join("MEDIA", "CSE", "USA"),
    os.path.join("MEDIA", "INTRODUCTION"),
    os.path.join("MEDIA", "STAFFROLL"),
    os.path.join("MEDIA", "TALK"),
    os.path.join("MEDIA2", "AUTHOR2"),
    os.path.join("MEDIA3", "ARC")
]

TALK_SKIP_Y2 = [
    os.path.join("MEDIA", "TALK", "MSG", "CABA"),
    os.path.join("MEDIA", "TALK", "MSG", "HOME", "TALK_HOMECLEAR"),
    os.path.join("MEDIA", "TALK", "MSG", "HOME", "TALK_HOMEMENU"),
    os.path.join("MEDIA", "TALK", "MSG", "HOME", "TALK_HOMEMOVIE"),
    os.path.join("MEDIA", "TALK", "MSG", "PAUSE", "ITEMINFO"),
    os.path.join("MEDIA", "TALK", "MSG", "PAUSE", "TALK_PAUSEMENU"),
    os.path.join("MEDIA2", "AUTHOR2", "CHAPTER"),
    os.path.join("MEDIA2", "AUTHOR2", "OGRE2_PROLOGUE")
]

TALK_SELF_Y2 = [
    os.path.join("MEDIA", "TALK", "MSG", "HOME", "TALK_HOMEMEMCARD"),
    os.path.join("MEDIA", "TALK", "MSG", "PAUSE", "TALK_PAUSECELLULAR"),
    os.path.join("MEDIA", "TALK", "MSG", "PAUSE", "TALK_PAUSECOMP_MG"),
    os.path.join("MEDIA", "TALK", "MSG", "PAUSE", "TALK_PAUSECOMPLETE"),
    os.path.join("MEDIA", "TALK", "MSG", "PAUSE", "TALK_PAUSEMAP"),
    os.path.join("MEDIA", "TALK", "MSG", "PAUSE", "TALK_PAUSERELATION"),
    os.path.join("MEDIA", "TALK", "MSG", "PAUSE", "TALK_PAUSESTATUS"),
    os.path.join("MEDIA", "TALK", "MSG", "TALK_CONTINUE"),
    os.path.join("MEDIA", "TALK", "MSG", "TALK_OPTION"),
    os.path.join("MEDIA", "TALK", "MSG", "TALK_SELECTMENU"),
    os.path.join("MEDIA", "TALK", "MSG", "TALK_TUTORIAL"),
    os.path.join("MEDIA", "TALK", "MSG", "TALK_TUTORIAL2")
]

TALK_HOLD_Y2 = [
    os.path.join("MEDIA", "TALK", "MSG", "ARMS"),
    os.path.join("MEDIA", "TALK", "MSG", "HACTARMS")
]

MOVIE_Y1 = [
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER01_001.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER03_001.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER03_005.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER03_007.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER04_002.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER04_008.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER07_007.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER10_004.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER10_022.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER11_004.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER11_013.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER12_003.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER14_007.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER15_009.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER15_010.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER16_002.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER16_007.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER16_011.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER16_015.SFD"),
    os.path.join("MEDIA2", "MOVIE", "AUTH_CHAPTER18_004B.SFD"),
    os.path.join("MEDIA2", "MOVIE", "CAPTION01.SFD"),
    os.path.join("MEDIA2", "MOVIE", "CAPTION02.SFD"),
    os.path.join("MEDIA2", "MOVIE", "CAPTION03.SFD"),
    os.path.join("MEDIA2", "MOVIE", "CAPTION04.SFD"),
    os.path.join("MEDIA2", "MOVIE", "CAPTION05.SFD"),
    os.path.join("MEDIA2", "MOVIE", "CAPTION06.SFD"),
    os.path.join("MEDIA2", "MOVIE", "CAPTION07.SFD"),
    os.path.join("MEDIA2", "MOVIE", "OPENING_MOVIE.SFD"),
    os.path.join("MEDIA2", "MOVIE", "SEGALOGO.SFD"),
    os.path.join("MEDIA2", "MOVIE", "W_OPENING_MOVIE.SFD"),
    os.path.join("MEDIA2", "MOVIE", "W_SEGALOGO.SFD"),
]

MOVIE_Y2 = [
    os.path.join("MEDIA5", "MOVIE2", "C01", "SCENE_01_0010.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C01", "SCENE_01_0015.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C01", "SCENE_01_0030.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C01", "SCENE_01_0068.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C02", "SCENE_02_0020.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C02", "SCENE_02_0030.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C02", "SCENE_02_0042.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C03", "SCENE_03_0028.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C03", "SCENE_03_0050.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C03", "SCENE_03_0078.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C09", "SCENE_09_0030.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C09", "SCENE_09_0070.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C09", "SCENE_09_0080.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C09", "SCENE_09_0105.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C10", "SCENE_10_0089.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C12", "SCENE_12_0070.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C12", "SCENE_12_0120.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C13", "SCENE_13_0018.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C13", "SCENE_13_0028.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C13", "SCENE_13_0105.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C14", "SCENE_14_0020.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C14", "SCENE_14_0080.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C14", "SCENE_14_0090.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C15", "SCENE_15_0030.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C15", "SCENE_15_0078.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "C17", "SCENE_17_0010.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "OGRE2_PROLOGUE01.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "OGRE2_PROLOGUE02.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "OGRE2_PROLOGUE03.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "OGRE2_PROLOGUE04.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "OPENING_MOVIE.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "SEGALOGO.SFD"),
    os.path.join("MEDIA5", "MOVIE2", "W_SEGALOGO.SFD")
]

VOICE_SE_Y1_JP = [
    os.path.join("MEDIA", "SE", "00008_VOICE2.DAT"),
    os.path.join("MEDIA", "SE", "00009_VOICE3.DAT"),
    os.path.join("MEDIA", "SE", "00010_VOICE4.DAT"),
    os.path.join("MEDIA", "SE", "00011_VOICE5.DAT"),
    os.path.join("MEDIA", "SE", "00021_VOICE8.DAT"),
    os.path.join("MEDIA", "SE", "00038_VOICE19.DAT"),
    os.path.join("MEDIA", "SE", "00039_VOICE20.DAT"),
    os.path.join("MEDIA", "SE", "00040_VOICE21.DAT"),
    os.path.join("MEDIA", "SE", "00045_VOICE26.DAT"),
    os.path.join("MEDIA", "SE", "00046_VOICE27.DAT"),
    os.path.join("MEDIA", "SE", "00056_VOICE37.DAT"),
    os.path.join("MEDIA", "SE", "00057_VOICE38.DAT"),
    os.path.join("MEDIA", "SE", "00067_VOICE48.DAT"),
    os.path.join("MEDIA", "SE", "02005_AMB05.DAT"),
    os.path.join("MEDIA", "SE", "02013_AMB13.DAT"),
    os.path.join("MEDIA", "SE", "02204_AMB204.DAT"),
    os.path.join("MEDIA", "SE", "10070_PEOPLE01.DAT"),
    os.path.join("MEDIA", "SE", "10071_PEOPLE02.DAT"),
    os.path.join("MEDIA", "SE", "10072_PEOPLE03.DAT"),
    os.path.join("MEDIA", "SE", "10073_PEOPLE04.DAT"),
    os.path.join("MEDIA", "SE", "10074_PEOPLE05.DAT"),
    os.path.join("MEDIA", "SE", "10075_PEOPLE06.DAT"),
    os.path.join("MEDIA", "SE", "10076_PEOPLE07.DAT"),
    os.path.join("MEDIA", "SE", "10077_PEOPLE08.DAT"),
    os.path.join("MEDIA", "SE", "10078_PEOPLE09.DAT"),
    os.path.join("MEDIA", "SE", "10079_PEOPLE10.DAT"),
    os.path.join("MEDIA", "SE", "10080_PEOPLE11.DAT"),
    os.path.join("MEDIA", "SE", "10092_PYACT1.DAT"),
    os.path.join("MEDIA", "SE", "10093_PYACT2.DAT"),
    os.path.join("MEDIA", "SE", "10094_PYACT3.DAT"),
    os.path.join("MEDIA", "SE", "10095_VOICE5.DAT"),
    os.path.join("MEDIA", "SE", "10096_VOICE9.DAT"),
    os.path.join("MEDIA", "SE", "10097_VOICE11.DAT"),
    os.path.join("MEDIA", "SE", "10098_VOICE3.DAT"),
    os.path.join("MEDIA", "SE", "10099_VOICE4.DAT"),
    os.path.join("MEDIA", "SE", "10100_VOICE7.DAT"),
    os.path.join("MEDIA", "SE", "10102_VOICE51.DAT"),
    os.path.join("MEDIA", "SE", "10103_VOICE52.DAT"),
    os.path.join("MEDIA", "SE", "10109_VOICE53.DAT"),
    os.path.join("MEDIA", "SE", "12000_BSEVE01.DAT"),
    os.path.join("MEDIA", "SE", "12001_BSEVE02.DAT"),
    os.path.join("MEDIA", "SE", "12002_BSEVE03.DAT"),
    os.path.join("MEDIA", "SE", "12003_BSEVE04.DAT"),
    os.path.join("MEDIA", "SE", "12004_BSEVE05.DAT"),
    os.path.join("MEDIA", "SE", "12005_BSEVE06.DAT"),
    os.path.join("MEDIA", "SE", "12006_BSEVE07.DAT"),
    os.path.join("MEDIA", "SE", "12007_BSEVE08.DAT"),
    os.path.join("MEDIA", "SE", "12008_BSEVE09.DAT"),
    os.path.join("MEDIA", "SE", "12009_BSEVE10.DAT"),
    os.path.join("MEDIA", "SE", "12010_BSEVE11.DAT"),
    os.path.join("MEDIA", "SE", "12011_BSEVE12.DAT"),
    os.path.join("MEDIA", "SE", "12012_BSEVE13.DAT"),
    os.path.join("MEDIA", "SE", "12013_BSEVE14.DAT"),
    os.path.join("MEDIA", "SE", "12014_BSEVE15.DAT"),
    os.path.join("MEDIA", "SE", "12015_BSEVE16.DAT"),
    os.path.join("MEDIA", "SE", "12016_BSEVE17.DAT"),
    os.path.join("MEDIA", "SE", "12017_BSEVE18.DAT"),
    os.path.join("MEDIA", "SE", "12018_BSEVE19.DAT"),
    os.path.join("MEDIA", "SE", "12019_BSEVE20.DAT"),
    os.path.join("MEDIA", "SE", "12020_BSEVE21.DAT"),
    os.path.join("MEDIA", "SE", "12021_BSEVE22.DAT"),
    os.path.join("MEDIA", "SE", "12022_BSEVE23.DAT"),
    os.path.join("MEDIA", "SE", "12023_BSEVE24.DAT"),
    os.path.join("MEDIA", "SE", "12024_BSEVE25.DAT"),
    os.path.join("MEDIA", "SE", "12025_BSEVE26.DAT"),
    os.path.join("MEDIA", "SE", "12026_BSEVE27.DAT"),
    os.path.join("MEDIA", "SE", "12027_BSEVE28.DAT"),
    os.path.join("MEDIA", "SE", "12028_BSEVE29.DAT"),
    os.path.join("MEDIA", "SE", "12029_BSEVE30.DAT"),
    os.path.join("MEDIA", "SE", "12030_BSEVE31.DAT"),
    os.path.join("MEDIA", "SESET", "SE_ADV_CLUB.DAT"),
    os.path.join("MEDIA", "SESET", "SE_ADV_DEBORA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_ADV_HSC.DAT"),
    os.path.join("MEDIA", "SESET", "SE_ADV_KAB.DAT"),
    os.path.join("MEDIA", "SESET", "SE_ADV_SERENA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_ADV_STRIP.DAT"),
    os.path.join("MEDIA", "SESET", "SE_ADV_TOBA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_AUTH_KEITAI.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_AOTA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_ARASE.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_ARI.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_BILLROOFTOP.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_BOTTAMASTER.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_CLUB.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_FUROUSYA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_HAYASHI.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_JACKAL.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_JAKA1.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_JAKA2.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_JERSEY_GANG.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_JINGU.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_KIMURA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_KINYU.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_KOROSIYA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_MAJIMA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_MAJIMA2.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_MIA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_NISHIKIYAMA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_OWNER.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_PRISONER.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_RAUKARLON.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_RED_LEADER.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_SHIMANO.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_SHINDO.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_SHISHO.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_SHOUTA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_TAKASHI.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_TEAMER.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_TETSU.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_UG.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_WHITE_LEADER.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_YASUDA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_YOPPARAI.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_YUUYA.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_ZAKO.DAT"),
    os.path.join("MEDIA", "SESET", "SE_BTL_ZAKO_THUNDER.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_BATTING.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CABARET_JEWEL.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CABARET_JEWEL2.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CABARET_JEWEL3.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CABARET_SHINE.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CABARET_SHINE2.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CABARET_SHINE3.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CARCHASE.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CASINO.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_CHOHAN.DAT"),
    os.path.join("MEDIA", "SESET", "SE_MINI_HEALTH.DAT")
]

VOICE_Y2_KR = [
    os.path.join("MEDIA2", "SOUND", "06", "NISE_KAZUKI_031.AHX"),
    os.path.join("MEDIA2", "SOUND", "06", "NISE_KAZUKI_032.AHX"),
    os.path.join("MEDIA2", "SOUND", "07", "KIM_001.AHX"),
    os.path.join("MEDIA2", "SOUND", "07", "KIM_006B.AHX"),
    os.path.join("MEDIA2", "SOUND", "07", "YANG_001.AHX"),
    os.path.join("MEDIA2", "SOUND", "07", "YANG_002.AHX"),
    os.path.join("MEDIA2", "SOUND", "ETC", "BOSS_002.AHX"),
    os.path.join("MEDIA2", "SOUND", "ETC", "BOSS_003.AHX"),
    os.path.join("MEDIA2", "SOUND", "ETC", "BOSS_004.AHX"),
    os.path.join("MEDIA2", "SOUND", "11", "MURAI_030.AHX"),
    os.path.join("MEDIA2", "SOUND", "16", "DEJIN_001.AHX"),
    os.path.join("MEDIA2", "SOUND", "16", "DEJIN_002.AHX"),
    os.path.join("MEDIA2", "SOUND", "16", "DEJIN_004.AHX"),
    os.path.join("MEDIA2", "SOUND", "16", "DEJIN_005.AHX"),
    os.path.join("MEDIA2", "SOUND", "16", "YONMIN_001.AHX"),
    os.path.join("MEDIA2", "SOUND", "16", "YONMIN_002.AHX")
]
